
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Program Files/LLVM/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      clang: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
      clang: error: unable to execute command: program not executable
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/4.0.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      clang++: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
      clang++: error: unable to execute command: program not executable
      clang++: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/4.0.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-whjcfs"
      binary: "C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-whjcfs"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-whjcfs'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/ProgramData/mingw64/mingw64/bin/mingw32-make.exe -f Makefile cmTC_5363c/fast
        C:/ProgramData/mingw64/mingw64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_5363c.dir\\build.make CMakeFiles/cmTC_5363c.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-whjcfs'
        Building C object CMakeFiles/cmTC_5363c.dir/CMakeCCompilerABI.c.obj
        C:\\PROGRA~1\\LLVM\\bin\\clang.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_5363c.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_5363c.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles\\cmTC_5363c.dir\\CMakeCCompilerABI.c.obj -c "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
        Linking C executable cmTC_5363c.exe
        "C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_link_script CMakeFiles\\cmTC_5363c.dir\\link.txt --verbose=1
        C:\\PROGRA~1\\LLVM\\bin\\clang.exe -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd  -v -Xlinker /subsystem:console -fuse-ld=lld-link @CMakeFiles\\cmTC_5363c.dir\\objects1.rsp -o cmTC_5363c.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_5363c.lib -Xlinker /pdb:C:\\Users\\meyer\\Repos\\low_rez_2025\\CMakeFiles\\CMakeScratch\\TryCompile-whjcfs\\cmTC_5363c.pdb -Xlinker /version:0.0 
        clang version 20.1.8
        Target: x86_64-pc-windows-msvc
        Thread model: posix
        InstalledDir: C:\\Program Files\\LLVM\\bin
         "C:\\\\Program Files\\\\LLVM\\\\bin\\\\lld-link" -out:cmTC_5363c.exe "-libpath:lib\\\\amd64" "-libpath:atlmfc\\\\lib\\\\amd64" "-libpath:C:\\\\Program Files\\\\LLVM\\\\lib\\\\clang\\\\20\\\\lib\\\\windows" -nologo -debug /subsystem:console CMakeFiles/cmTC_5363c.dir/CMakeCCompilerABI.c.obj /MANIFEST:EMBED /implib:cmTC_5363c.lib "/pdb:C:\\\\Users\\\\meyer\\\\Repos\\\\low_rez_2025\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-whjcfs\\\\cmTC_5363c.pdb" /version:0.0
        lld-link: error: could not open 'msvcrtd.lib': no such file or directory
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        mingw32-make[1]: *** [CMakeFiles\\cmTC_5363c.dir\\build.make:103: cmTC_5363c.exe] Error 1
        mingw32-make[1]: Leaving directory 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-whjcfs'
        mingw32-make: *** [Makefile:133: cmTC_5363c/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe"
    directories:
      source: "C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-0vivyg"
      binary: "C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-0vivyg"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-0vivyg'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/ProgramData/mingw64/mingw64/bin/mingw32-make.exe -f Makefile cmTC_16506/fast
        C:/ProgramData/mingw64/mingw64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_16506.dir\\build.make CMakeFiles/cmTC_16506.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-0vivyg'
        Building C object CMakeFiles/cmTC_16506.dir/testCCompiler.c.obj
        C:\\PROGRA~1\\LLVM\\bin\\clang.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_16506.dir/testCCompiler.c.obj -MF CMakeFiles\\cmTC_16506.dir\\testCCompiler.c.obj.d -o CMakeFiles\\cmTC_16506.dir\\testCCompiler.c.obj -c C:\\Users\\meyer\\Repos\\low_rez_2025\\CMakeFiles\\CMakeScratch\\TryCompile-0vivyg\\testCCompiler.c
        Linking C executable cmTC_16506.exe
        "C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_link_script CMakeFiles\\cmTC_16506.dir\\link.txt --verbose=1
        C:\\PROGRA~1\\LLVM\\bin\\clang.exe -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console -fuse-ld=lld-link @CMakeFiles\\cmTC_16506.dir\\objects1.rsp -o cmTC_16506.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_16506.lib -Xlinker /pdb:C:\\Users\\meyer\\Repos\\low_rez_2025\\CMakeFiles\\CMakeScratch\\TryCompile-0vivyg\\cmTC_16506.pdb -Xlinker /version:0.0  @CMakeFiles\\cmTC_16506.dir\\linkLibs.rsp
        lld-link: error: could not open 'kernel32.lib': no such file or directory
        lld-link: error: could not open 'user32.lib': no such file or directory
        lld-link: error: could not open 'gdi32.lib': no such file or directory
        lld-link: error: could not open 'winspool.lib': no such file or directory
        lld-link: error: could not open 'shell32.lib': no such file or directory
        lld-link: error: could not open 'ole32.lib': no such file or directory
        lld-link: error: could not open 'oleaut32.lib': no such file or directory
        lld-link: error: could not open 'uuid.lib': no such file or directory
        lld-link: error: could not open 'comdlg32.lib': no such file or directory
        lld-link: error: could not open 'advapi32.lib': no such file or directory
        lld-link: error: could not open 'oldnames.lib': no such file or directory
        lld-link: error: could not open 'msvcrtd.lib': no such file or directory
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        mingw32-make[1]: *** [CMakeFiles\\cmTC_16506.dir\\build.make:104: cmTC_16506.exe] Error 1
        mingw32-make[1]: Leaving directory 'C:/Users/meyer/Repos/low_rez_2025/CMakeFiles/CMakeScratch/TryCompile-0vivyg'
        mingw32-make: *** [Makefile:133: cmTC_16506/fast] Error 2
        
      exitCode: 2
...
